// Code generated by "stringer -type=CardType"; DO NOT EDIT

package main

import "fmt"

const _CardType_name = "NumberCardFaceCardAceCardJokerCard"

var _CardType_index = [...]uint8{0, 10, 18, 25, 34}

func (i CardType) String() string {
	if i < 0 || i >= CardType(len(_CardType_index)-1) {
		return fmt.Sprintf("CardType(%d)", i)
	}
	return _CardType_name[_CardType_index[i]:_CardType_index[i+1]]
}
